# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/vertexai/property/batchpredictionjob_explanation_spec_parameters_examples'
require 'google/vertexai/property/batchpredictionjob_explanation_spec_parameters_examples_example_gcs_source'
require 'google/vertexai/property/batchpredictionjob_explanation_spec_parameters_examples_example_gcs_source_gcs_source'
require 'google/vertexai/property/batchpredictionjob_explanation_spec_parameters_examples_presets'
require 'google/vertexai/property/batchpredictionjob_explanation_spec_parameters_integrated_gradients_attribution'
require 'google/vertexai/property/batchpredictionjob_espigabb_config'
require 'google/vertexai/property/batchpredictionjob_espigasg_config'
require 'google/vertexai/property/batchpredictionjob_espigasgcfn_sigma'
require 'google/vertexai/property/batchpredictionjob_espigasgcfnsn_sigma'
require 'google/vertexai/property/batchpredictionjob_explanation_spec_parameters_sampled_shapley_attribution'
require 'google/vertexai/property/batchpredictionjob_explanation_spec_parameters_xrai_attribution'
require 'google/vertexai/property/batchpredictionjob_explanation_spec_parameters_xrai_attribution_blur_baseline_config'
require 'google/vertexai/property/batchpredictionjob_explanation_spec_parameters_xrai_attribution_smooth_grad_config'
require 'google/vertexai/property/batchpredictionjob_espxasgcfn_sigma'
require 'google/vertexai/property/batchpredictionjob_espxasgcfnsn_sigma'
module GoogleInSpec
  module VertexAI
    module Property
      class BatchPredictionJobExplanationSpecParameters
        attr_reader :output_indices

        attr_reader :examples

        attr_reader :xrai_attribution

        attr_reader :top_k

        attr_reader :integrated_gradients_attribution

        attr_reader :sampled_shapley_attribution

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @output_indices = args['outputIndices']
          @examples = GoogleInSpec::VertexAI::Property::BatchPredictionJobExplanationSpecParametersExamples.new(args['examples'], to_s)
          @xrai_attribution = GoogleInSpec::VertexAI::Property::BatchPredictionJobExplanationSpecParametersXraiAttribution.new(args['xraiAttribution'], to_s)
          @top_k = args['topK']
          @integrated_gradients_attribution = GoogleInSpec::VertexAI::Property::BatchPredictionJobExplanationSpecParametersIntegratedGradientsAttribution.new(args['integratedGradientsAttribution'], to_s)
          @sampled_shapley_attribution = GoogleInSpec::VertexAI::Property::BatchPredictionJobExplanationSpecParametersSampledShapleyAttribution.new(args['sampledShapleyAttribution'], to_s)
        end

        def to_s
          "#{@parent_identifier} BatchPredictionJobExplanationSpecParameters"
        end
      end
    end
  end
end
