

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module VertexAI
    module Property
      class BatchPredictionJobPartialFailures
        attr_reader :details

        attr_reader :code

        attr_reader :message

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @details = args["details"]
          @code = args["code"]
          @message = args["message"]
        end

        def to_s
          "#{@parent_identifier} BatchPredictionJobPartialFailures"
        end
      end

      class BatchPredictionJobPartialFailuresArray
        def self.parse(value, parent_identifier)
          return if value.nil?
          return BatchPredictionJobPartialFailures.new(value, parent_identifier) unless value.is_a?(::Array)
          value.map { |v| BatchPredictionJobPartialFailures.new(v, parent_identifier) }
        end
      end
    end
  end
end
