# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/dlp/property/dt_config_info_type_tf'
require 'google/dlp/property/dt_config_info_type_tf_tf'
module GoogleInSpec
  module DLP
    module Property
      class DTConfig
        attr_reader :info_type_tf

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @info_type_tf = GoogleInSpec::DLP::Property::DTConfigInfoTypeTf.new(args['infoTypeTf'], to_s)
        end

        def to_s
          "#{@parent_identifier} DTConfig"
        end
      end
    end
  end
end
