# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/dlp/property/job_act_det_dt_det_req_opt_snapshot_img_rt_dt_con_rec_tf_rec_sup_con_exp_con_con_new_val_date_val'
require 'google/dlp/property/job_act_det_dt_det_req_opt_snapshot_img_rt_dt_con_rec_tf_rec_sup_con_exp_con_con_new_val_time_val'
module GoogleInSpec
  module DLP
    module Property
      class JobActDetDtDetReqOptSnapshotImgRtDtConRecTfRecSupConExpConConNewVal
        attr_reader :integer_val

        attr_reader :float_val

        attr_reader :string_val

        attr_reader :boolean_val

        attr_reader :timestamp_val

        attr_reader :time_val

        attr_reader :date_val

        attr_reader :day_of_week_val

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @integer_val = args['integerVal']
          @float_val = args['floatVal']
          @string_val = args['stringVal']
          @boolean_val = args['booleanVal']
          @timestamp_val = args['timestampVal']
          @time_val = GoogleInSpec::DLP::Property::JobActDetDtDetReqOptSnapshotImgRtDtConRecTfRecSupConExpConConNewValTimeVal.new(args['timeVal'], to_s)
          @date_val = GoogleInSpec::DLP::Property::JobActDetDtDetReqOptSnapshotImgRtDtConRecTfRecSupConExpConConNewValDateVal.new(args['dateVal'], to_s)
          @day_of_week_val = args['dayOfWeekVal']
        end

        def to_s
          "#{@parent_identifier} JobActDetDtDetReqOptSnapshotImgRtDtConRecTfRecSupConExpConConNewVal"
        end
      end
    end
  end
end
