# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/storage/property/bucket_lifecycle_rule_action'
require 'google/storage/property/bucket_lifecycle_rule_condition'
module GoogleInSpec
  module Storage
    module Property
      class BucketLifecycleRule
        attr_reader :action

        attr_reader :condition

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @action = GoogleInSpec::Storage::Property::BucketLifecycleRuleAction.new(args['action'], to_s)
          @condition = GoogleInSpec::Storage::Property::BucketLifecycleRuleCondition.new(args['condition'], to_s)
        end

        def to_s
          "#{@parent_identifier} BucketLifecycleRule"
        end
      end

      class BucketLifecycleRuleArray
        def self.parse(value, parent_identifier)
          return if value.nil?
          return BucketLifecycleRule.new(value, parent_identifier) unless value.is_a?(::Array)
          value.map { |v| BucketLifecycleRule.new(v, parent_identifier) }
        end
      end
    end
  end
end
