# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/compute/property/machineimage_instance_properties_disks_initialize_params_labels'
require 'google/compute/property/machineimage_instance_properties_disks_initialize_params_resource_manager_tags'
require 'google/compute/property/machineimage_instance_properties_disks_initialize_params_source_image_encryption_key'
require 'google/compute/property/machineimage_instance_properties_disks_initialize_params_source_snapshot_encryption_key'
module GoogleInSpec
  module Compute
    module Property
      class MachineImageInstancePropertiesDisksInitializeParams
        attr_reader :disk_name

        attr_reader :source_image

        attr_reader :disk_size_gb

        attr_reader :disk_type

        attr_reader :source_image_encryption_key

        attr_reader :labels

        attr_reader :source_snapshot

        attr_reader :source_snapshot_encryption_key

        attr_reader :description

        attr_reader :replica_zones

        attr_reader :resource_policies

        attr_reader :on_update_action

        attr_reader :provisioned_iops

        attr_reader :licenses

        attr_reader :architecture

        attr_reader :resource_manager_tags

        attr_reader :provisioned_throughput

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @disk_name = args['diskName']
          @source_image = args['sourceImage']
          @disk_size_gb = args['diskSizeGb']
          @disk_type = args['diskType']
          @source_image_encryption_key = GoogleInSpec::Compute::Property::MachineImageInstancePropertiesDisksInitializeParamsSourceImageEncryptionKey.new(args['sourceImageEncryptionKey'], to_s)
          @labels = GoogleInSpec::Compute::Property::MachineImageInstancePropertiesDisksInitializeParamsLabels.new(args['labels'], to_s)
          @source_snapshot = args['sourceSnapshot']
          @source_snapshot_encryption_key = GoogleInSpec::Compute::Property::MachineImageInstancePropertiesDisksInitializeParamsSourceSnapshotEncryptionKey.new(args['sourceSnapshotEncryptionKey'], to_s)
          @description = args['description']
          @replica_zones = args['replicaZones']
          @resource_policies = args['resourcePolicies']
          @on_update_action = args['onUpdateAction']
          @provisioned_iops = args['provisionedIops']
          @licenses = args['licenses']
          @architecture = args['architecture']
          @resource_manager_tags = GoogleInSpec::Compute::Property::MachineImageInstancePropertiesDisksInitializeParamsResourceManagerTags.new(args['resourceManagerTags'], to_s)
          @provisioned_throughput = args['provisionedThroughput']
        end

        def to_s
          "#{@parent_identifier} MachineImageInstancePropertiesDisksInitializeParams"
        end
      end
    end
  end
end
