# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module Compute
    module Property
      class RegionSecurityPolicyRulesHeaderActionRequestHeadersToAdds
        attr_reader :header_name

        attr_reader :header_value

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @header_name = args['headerName']
          @header_value = args['headerValue']
        end

        def to_s
          "#{@parent_identifier} RegionSecurityPolicyRulesHeaderActionRequestHeadersToAdds"
        end
      end

      class RegionSecurityPolicyRulesHeaderActionRequestHeadersToAddsArray
        def self.parse(value, parent_identifier)
          return if value.nil?
          return RegionSecurityPolicyRulesHeaderActionRequestHeadersToAdds.new(value, parent_identifier) unless value.is_a?(::Array)
          value.map { |v| RegionSecurityPolicyRulesHeaderActionRequestHeadersToAdds.new(v, parent_identifier) }
        end
      end
    end
  end
end
