# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/container/property/cluster_master_auth_client_certificate_config'
module GoogleInSpec
  module Container
    module Property
      class ClusterMasterAuth
        attr_reader :username, :password, :client_certificate_config, :cluster_ca_certificate, :client_certificate, :client_key

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @username = args['username']
          @password = args['password']
          @client_certificate_config = GoogleInSpec::Container::Property::ClusterMasterAuthClientCertificateConfig.new(args['clientCertificateConfig'], to_s)
          @cluster_ca_certificate = args['clusterCaCertificate']
          @client_certificate = args['clientCertificate']
          @client_key = args['clientKey']
        end

        def to_s
          "#{@parent_identifier} ClusterMasterAuth"
        end
      end
    end
  end
end
