# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module Container
    module Property
      class RegionalNodePoolManagementUpgradeOptions
        attr_reader :auto_upgrade_start_time

        attr_reader :description

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @auto_upgrade_start_time = parse_time_string(args['autoUpgradeStartTime'])
          @description = args['description']
        end

        def to_s
          "#{@parent_identifier} RegionalNodePoolManagementUpgradeOptions"
        end
      end
    end
  end
end
