# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/dataproc/property/projectlocationworkflowtemplate_placement_managed_cluster_config_gke_cluster_config_node_pool_target_node_pool_config'
require 'google/dataproc/property/projectlocationworkflowtemplate_placement_managed_cluster_config_gke_cluster_config_node_pool_target_node_pool_config_autoscaling'
require 'google/dataproc/property/projectlocationworkflowtemplate_placement_managed_cluster_config_gke_cluster_config_node_pool_target_node_pool_config_config'
require 'google/dataproc/property/projectlocationworkflowtemplate_placement_managed_cluster_config_gke_cluster_config_node_pool_target_node_pool_config_config_accelerators'
module GoogleInSpec
  module Dataproc
    module Property
      class ProjectLocationWorkflowTemplatePlacementManagedClusterConfigGkeClusterConfigNodePoolTarget
        attr_reader :node_pool

        attr_reader :roles

        attr_reader :node_pool_config

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @node_pool = args['nodePool']
          @roles = args['roles']
          @node_pool_config = GoogleInSpec::Dataproc::Property::ProjectLocationWorkflowTemplatePlacementManagedClusterConfigGkeClusterConfigNodePoolTargetNodePoolConfig.new(args['nodePoolConfig'], to_s)
        end

        def to_s
          "#{@parent_identifier} ProjectLocationWorkflowTemplatePlacementManagedClusterConfigGkeClusterConfigNodePoolTarget"
        end
      end

      class ProjectLocationWorkflowTemplatePlacementManagedClusterConfigGkeClusterConfigNodePoolTargetArray
        def self.parse(value, parent_identifier)
          return if value.nil?
          return ProjectLocationWorkflowTemplatePlacementManagedClusterConfigGkeClusterConfigNodePoolTarget.new(value, parent_identifier) unless value.is_a?(::Array)
          value.map { |v| ProjectLocationWorkflowTemplatePlacementManagedClusterConfigGkeClusterConfigNodePoolTarget.new(v, parent_identifier) }
        end
      end
    end
  end
end
