# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/dataproc/property/workflowtemplate_gke_cluster_config_node_pool_target_node_pool_config_config_accelerators'
module GoogleInSpec
  module Dataproc
    module Property
      class WorkflowTemplateGkeClusterConfigNodePoolTargetNodePoolConfigConfig
        attr_reader :machine_type

        attr_reader :local_ssd_count

        attr_reader :preemptible

        attr_reader :accelerators

        attr_reader :min_cpu_platform

        attr_reader :boot_disk_kms_key

        attr_reader :spot

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @machine_type = args['machineType']
          @local_ssd_count = args['localSsdCount']
          @preemptible = args['preemptible']
          @accelerators = GoogleInSpec::Dataproc::Property::WorkflowTemplateGkeClusterConfigNodePoolTargetNodePoolConfigConfigAcceleratorsArray.parse(args['accelerators'], to_s)
          @min_cpu_platform = args['minCpuPlatform']
          @boot_disk_kms_key = args['bootDiskKmsKey']
          @spot = args['spot']
        end

        def to_s
          "#{@parent_identifier} WorkflowTemplateGkeClusterConfigNodePoolTargetNodePoolConfigConfig"
        end
      end
    end
  end
end
