AllCops:
  TargetRubyVersion: 2.6
  Exclude:
  - Gemfile
  - generate/Gemfile
  - Rakefile
  - 'test/**/*'
  - 'examples/**/*'
  - 'vendor/**/*'
  - 'lib/bundles/inspec-init/templates/**/*'
Documentation:
  Enabled: false
Encoding:
  Enabled: true
HashSyntax:
  Enabled: true
ClassLength:
  Max: 200
  Exclude:
  - 'libraries/google_compute_firewall.rb'
LineLength:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
MethodLength:
  Max: 45
NumericLiterals:
  MinDigits: 10
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': '{}'
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '{}'
    '%W': ()
    '%x': ()
Layout/HashAlignment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/Not:
  Enabled: false
Naming/FileName:
  Enabled: true
  Regex: !ruby/regexp '/^.{3,90}$/'
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/NegatedIf:
  Enabled: false
Style/UnlessElse:
  Enabled: false
BlockDelimiters:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
