# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/dlp/property/jobtrigger_triggers_schedule'
module GoogleInSpec
  module DLP
    module Property
      class JobTriggerTriggers
        attr_reader :schedule

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @schedule = GoogleInSpec::DLP::Property::JobTriggerTriggersSchedule.new(args['schedule'], to_s)
        end

        def to_s
          "#{@parent_identifier} JobTriggerTriggers"
        end
      end

      class JobTriggerTriggersArray
        def self.parse(value, parent_identifier)
          return if value.nil?
          return JobTriggerTriggers.new(value, parent_identifier) unless value.is_a?(::Array)
          value.map { |v| JobTriggerTriggers.new(v, parent_identifier) }
        end
      end
    end
  end
end
