# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/dataprocmetastore/property/projectlocationservice_scaling_config_autoscaling_config'
require 'google/dataprocmetastore/property/projectlocationservice_scaling_config_autoscaling_config_limit_config'
module GoogleInSpec
  module DataprocMetastore
    module Property
      class ProjectLocationServiceScalingConfig
        attr_reader :instance_size

        attr_reader :scaling_factor

        attr_reader :autoscaling_config

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @instance_size = args['instanceSize']
          @scaling_factor = args['scalingFactor']
          @autoscaling_config = GoogleInSpec::DataprocMetastore::Property::ProjectLocationServiceScalingConfigAutoscalingConfig.new(args['autoscalingConfig'], to_s)
        end

        def to_s
          "#{@parent_identifier} ProjectLocationServiceScalingConfig"
        end
      end
    end
  end
end
