# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module DataprocMetastore
    module Property
      class ProjectLocationServiceScheduledBackupLatestBackup
        attr_reader :backup_id

        attr_reader :start_time

        attr_reader :state

        attr_reader :duration

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @backup_id = args['backupId']
          @start_time = args['startTime']
          @state = args['state']
          @duration = args['duration']
        end

        def to_s
          "#{@parent_identifier} ProjectLocationServiceScheduledBackupLatestBackup"
        end
      end
    end
  end
end
