# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_compute_service_attachment resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')

  service_attachment = input('service_attachment', value: {
  "project": "value_project",
  "region": "value_region",
  "service_attachment": "value_serviceattachment",
  "kind": "value_kind",
  "id": "value_id",
  "creation_timestamp": "value_creationtimestamp",
  "name": "value_name",
  "description": "value_description",
  "self_link": "value_selflink",
  "producer_forwarding_rule": "value_producerforwardingrule",
  "target_service": "value_targetservice",
  "connection_preference": "value_connectionpreference",
  "fingerprint": "value_fingerprint"
}, description: 'service_attachment description')
control 'google_compute_service_attachment-1.0' do
  impact 1.0
  title 'google_compute_service_attachment resource test'

  describe google_compute_service_attachment(project: gcp_project_id, region: service_attachment['region'], serviceAttachment: service_attachment['serviceAttachment']) do
  	it { should exist }
  	its('kind') { should cmp service_attachment['kind'] }
  	its('id') { should cmp service_attachment['id'] }
  	its('creation_timestamp') { should cmp service_attachment['creation_timestamp'] }
  	its('name') { should cmp service_attachment['name'] }
  	its('description') { should cmp service_attachment['description'] }
  	its('self_link') { should cmp service_attachment['self_link'] }
  	its('region') { should cmp service_attachment['region'] }
  	its('producer_forwarding_rule') { should cmp service_attachment['producer_forwarding_rule'] }
  	its('target_service') { should cmp service_attachment['target_service'] }
  	its('connection_preference') { should cmp service_attachment['connection_preference'] }
  	its('fingerprint') { should cmp service_attachment['fingerprint'] }

  end

  describe google_compute_service_attachment(project: gcp_project_id, region: service_attachment['region'], serviceAttachment: service_attachment['serviceAttachment']) do
  	it { should_not exist }
  end
end
