# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_dataproc_metastore_project_location_federation resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')
project_location_federation = input('project_location_federation', value: {
  "name": "value_name",
  "parent": "value_parent",
  "create_time": "value_createtime",
  "update_time": "value_updatetime",
  "version": "value_version",
  "endpoint_uri": "value_endpointuri",
  "state": "value_state",
  "state_message": "value_statemessage",
  "uid": "value_uid"
}, description: 'project_location_federation description')
control 'google_dataproc_metastore_project_location_federation-1.0' do
  impact 1.0
  title 'google_dataproc_metastore_project_location_federation resource test'

  describe google_dataproc_metastore_project_location_federation(name: project_location_federation['name']) do
  	it { should exist }
  	its('name') { should cmp project_location_federation['name'] }
  	its('create_time') { should cmp project_location_federation['create_time'] }
  	its('update_time') { should cmp project_location_federation['update_time'] }
  	its('version') { should cmp project_location_federation['version'] }
  	its('endpoint_uri') { should cmp project_location_federation['endpoint_uri'] }
  	its('state') { should cmp project_location_federation['state'] }
  	its('state_message') { should cmp project_location_federation['state_message'] }
  	its('uid') { should cmp project_location_federation['uid'] }

  end

  describe google_dataproc_metastore_project_location_federation(name: "does_not_exit") do
  	it { should_not exist }
  end
end
