# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_dataproc_jobs resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')

  job = input('job', value: {
  "job_id": "value_jobid",
  "project_id": "value_projectid",
  "region": "value_region",
  "driver_output_resource_uri": "value_driveroutputresourceuri",
  "driver_control_files_uri": "value_drivercontrolfilesuri",
  "job_uuid": "value_jobuuid"
}, description: 'job description')
control 'google_dataproc_jobs-1.0' do
  impact 1.0
  title 'google_dataproc_jobs resource test'

    describe google_dataproc_jobs() do
      it { should exist }
    end
end
