# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_vertex_ai_featurestores resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')

  featurestore = input('featurestore', value: {
  "name": "value_name",
  "region": "value_region",
  "parent": "value_parent",
  "state": "value_state",
  "create_time": "value_createtime",
  "etag": "value_etag",
  "update_time": "value_updatetime"
}, description: 'featurestore description')
control 'google_vertex_ai_featurestores-1.0' do
  impact 1.0
  title 'google_vertex_ai_featurestores resource test'

      describe google_vertex_ai_featurestores(parent: "projects/#{gcp_project_id}/locations/#{featurestore['region']}", region: featurestore['region']) do
      it { should exist }
    end
end
