# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_dataproc_batches resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')

  batch = input('batch', value: {
  "name": "value_name",
  "parent": "value_parent",
  "uuid": "value_uuid",
  "create_time": "value_createtime",
  "state": "value_state",
  "state_message": "value_statemessage",
  "state_time": "value_statetime",
  "creator": "value_creator",
  "operation": "value_operation"
}, description: 'batch description')
control 'google_dataproc_batches-1.0' do
  impact 1.0
  title 'google_dataproc_batches resource test'

      describe google_dataproc_batches(parent: batch['parent']) do
      it { should exist }
    end
end
