# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title "Test GCP google_ml_engine_model resource."

gcp_project_id = attribute(:gcp_project_id, default: "gcp_project_id", description: "The GCP project identifier.")
gcp_location = attribute(:gcp_location, default: "gcp_location", description: "The GCP project region.")
ml_model = attribute("ml_model", default: {
  "name": "ml_model",
  "region": "us-central1",
  "description": "My awesome ML model",
  "online_prediction_logging": true,
  "online_prediction_console_logging": true,
}, description: "Machine learning model definition")
control "google_ml_engine_model-1.0" do
  impact 1.0
  title "google_ml_engine_model resource test"

  describe google_ml_engine_model(project: gcp_project_id, name: ml_model["name"]) do
    it { should exist }
    its("description") { should cmp ml_model["description"] }
    its("regions") { should include ml_model["region"] }
    its("online_prediction_logging") { should cmp ml_model["online_prediction_logging"] }
    its("online_prediction_console_logging") { should cmp ml_model["online_prediction_console_logging"] }
  end

  describe google_ml_engine_model(project: gcp_project_id, name: "nonexistent") do
    it { should_not exist }
  end
end
