# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_compute_security_policies resource.'

gcp_project_id = attribute(:gcp_project_id, default: 'gcp_project_id', description: 'The GCP project identifier.')
security_policy = attribute('security_policy', default: {
  "name": "sec-policy",
  "action": "deny(403)",
  "priority": "1000",
  "ip_range": "9.9.9.0/24",
  "description": "my description"
}, description: 'Security Policy description')
control 'google_compute_security_policies-1.0' do
  impact 1.0
  title 'google_compute_security_policies resource test'

  describe google_compute_security_policies(project: gcp_project_id) do
    its('count') { should be >= 1 }
    its('names') { should include security_policy['name'] }
  end
end
