# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_compute_reservations resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')

  reservation = input('reservation', value: {
  "project": "value_project",
  "reservation": "value_reservation",
  "zone": "value_zone",
  "kind": "value_kind",
  "id": "value_id",
  "creation_timestamp": "value_creationtimestamp",
  "self_link": "value_selflink",
  "self_link_with_id": "value_selflinkwithid",
  "description": "value_description",
  "name": "value_name",
  "commitment": "value_commitment",
  "status": "value_status",
  "delete_at_time": "value_deleteattime"
}, description: 'reservation description')
control 'google_compute_reservations-1.0' do
  impact 1.0
  title 'google_compute_reservations resource test'

      describe google_compute_reservations(project: gcp_project_id, zone: reservation['zone']) do
      it { should exist }
    end
end
