# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_compute_target_vpn_gateways resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')

  target_vpn_gateway = input('target_vpn_gateway', value: {
  "project": "value_project",
  "region": "value_region",
  "target_vpn_gateway": "value_targetvpngateway",
  "kind": "value_kind",
  "id": "value_id",
  "creation_timestamp": "value_creationtimestamp",
  "name": "value_name",
  "description": "value_description",
  "network": "value_network",
  "status": "value_status",
  "self_link": "value_selflink",
  "label_fingerprint": "value_labelfingerprint"
}, description: 'target_vpn_gateway description')
control 'google_compute_target_vpn_gateways-1.0' do
  impact 1.0
  title 'google_compute_target_vpn_gateways resource test'

      describe google_compute_target_vpn_gateways(project: gcp_project_id, region: target_vpn_gateway['region']) do
      it { should exist }
    end
end
