# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_vertex_ai_metadata_stores_contexts resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')

  metadata_stores_context = input('metadata_stores_context', value: {
  "name": "autologging-experiment-w0apl7la-autologging-tf-experiment-w0apl7la",
  "region": "us-central1",
  "parent": "projects/165434197229/locations/us-central1/metadataStores/default/contexts/",
  "metadataStore": "default",
  "schema_title": "system.ExperimentRun",
  "etag": "value_etag",
  "description": "value_description",
  "display_name": "autologging-tf-experiment-w0apl7la",
  "schema_version": "value_schemaversion",
  "create_time": "value_createtime",
  "update_time": "value_updatetime"
}, description: 'metadata_stores_context description')
control 'google_vertex_ai_metadata_stores_contexts-1.0' do
  impact 1.0
  title 'google_vertex_ai_metadata_stores_contexts resource test'

      describe google_vertex_ai_metadata_stores_contexts(parent: "projects/#{gcp_project_id}/locations/#{metadata_stores_context['region']}/metadataStores/#{metadata_stores_context['metadataStore']}", region: metadata_stores_context['region']) do
      it { should exist }
    end
end
