# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_iam_project_service_account_key resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')

  project_service_account_key = input('project_service_account_key', value: {
  "name": "projects/ppradhan/serviceAccounts/myaccount@ppradhan.iam.gserviceaccount.com/keys/39cb9a8b59050acc5f06d4e1a7635d7d6c588ba1",
  "name_plural": "projects/ppradhan/serviceAccounts/myaccount@ppradhan.iam.gserviceaccount.com",
  "key_algorithm": "KEY_ALG_RSA_2048",
  "valid_before_time": "9999-12-31T23:59:59Z",
  "key_origin": "GOOGLE_PROVIDED",
  "key_type": "USER_MANAGED"
}, description: 'project_service_account_key description')
control 'google_iam_project_service_account_key-1.0' do
  impact 1.0
  title 'google_iam_project_service_account_key resource test'

  describe google_iam_project_service_account_key(name: project_service_account_key['name']) do
  	it { should exist }
  	its('name') { should cmp project_service_account_key['name'] }
  	its('key_algorithm') { should cmp project_service_account_key['key_algorithm'] }
  	its('valid_before_time') { should cmp project_service_account_key['valid_before_time'] }
  	its('key_origin') { should cmp project_service_account_key['key_origin'] }
  	its('key_type') { should cmp project_service_account_key['key_type'] }
  end

  describe google_iam_project_service_account_key(name: "does_not_exit") do
  	it { should_not exist }
  end
end
