# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_compute_health_check_service resource.'

gcp_project_id = attribute(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')
region_health_check_service = attribute('region_health_check_service', value: {
  "name": "instance-group-2",
  "region": "us-central1",
  "health_status_aggregation_policy": "NO_AGGREGATION"
}, description: 'HealthCheckService resources that have been configured for the specified project in the given region')
control 'google_compute_health_check_service-1.0' do
  impact 1.0
  title 'google_compute_health_check_service resource test'

  describe google_compute_health_check_service(project: gcp_project_id, region: region_health_check_service['region'], name: region_health_check_service['name']) do
  it { should exist }
  its('name') { should eq region_health_check_service['name'] }
  its('health_status_aggregation_policy') { should eq region_health_check_service['health_status_aggregation_policy'] }
  end

  describe google_compute_health_check_service(project: gcp_project_id, region: region_health_check_service['region'], name: 'nonexistent') do
  it { should_not exist }
  end
end
