# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_cloudkms_project_location_key_ring resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')

  project_location_key_ring = input('project_location_key_ring', value: {
  "name": "value_name",
  "parent": "value_parent",
  "create_time": "value_createtime"
}, description: 'project_location_key_ring description')
control 'google_cloudkms_project_location_key_ring-1.0' do
  impact 1.0
  title 'google_cloudkms_project_location_key_ring resource test'

  describe google_cloudkms_project_location_key_ring(name: project_location_key_ring['name']) do
  	it { should exist }
  	its('name') { should cmp project_location_key_ring['name'] }
  	its('create_time') { should cmp project_location_key_ring['create_time'] }

  end

  describe google_cloudkms_project_location_key_ring(name: "does_not_exit") do
  	it { should_not exist }
  end
end
