# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_apigee_organization_instance_attachment resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')

  organization_instance_attachment = input('organization_instance_attachment', value: {
  "name": "c4452279-f4dd-473c-b50d-de21bec8147b",
  "parent": "organizations/ppradhan/instances/us-central1",
  "environment": "inspec-test-env",
  "created_at": "1728297911815"
}, description: 'organization_instance_attachment description')
control 'google_apigee_organization_instance_attachment-1.0' do
  impact 1.0
  title 'google_apigee_organization_instance_attachment resource test'

  describe google_apigee_organization_instance_attachment(name: organization_instance_attachment['name']) do
  	it { should exist }
  	its('name') { should cmp organization_instance_attachment['name'] }
  	its('environment') { should cmp organization_instance_attachment['environment'] }
  	its('created_at') { should cmp organization_instance_attachment['created_at'] }

  end

  describe google_apigee_organization_instance_attachment(name: "does_not_exit") do
  	it { should_not exist }
  end
end
