# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_compute_machine_images resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')

  machine_image = input('machine_image', value: {
  "project": "ppradhan",
  "kind": "compute#machineImage",
  "id": "7552526330490377685",
  "creation_timestamp": "value_creationtimestamp",
  "name": "image-1",
  "description": "value_description",
  "self_link": "value_selflink",
  "source_instance": "value_sourceinstance",
  "status": "value_status",
  "total_storage_bytes": "value_totalstoragebytes"
}, description: 'machine_image description')
control 'google_compute_machine_images-1.0' do
  impact 1.0
  title 'google_compute_machine_images resource test'

    describe google_compute_machine_images(project: gcp_project_id) do
      it { should exist }
    end
end
