# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_vertex_ai_featurestore resource.'

gcp_project_id = input(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')

  featurestore = input('featurestore', value: {
  "name": "value_name",
  "region": "value_region",
  "parent": "value_parent",
  "state": "value_state",
  "create_time": "value_createtime",
  "etag": "value_etag",
  "update_time": "value_updatetime"
}, description: 'featurestore description')
control 'google_vertex_ai_featurestore-1.0' do
  impact 1.0
  title 'google_vertex_ai_featurestore resource test'

  describe google_vertex_ai_featurestore(name: "projects/#{gcp_project_id}/locations/#{featurestore['region']}/featurestores/#{featurestore['name']}", region: featurestore['region']) do
  	it { should exist }
  	its('state') { should cmp featurestore['state'] }
  	its('create_time') { should cmp featurestore['create_time'] }
  	its('etag') { should cmp featurestore['etag'] }
  	its('update_time') { should cmp featurestore['update_time'] }
  	its('name') { should cmp featurestore['name'] }

  end

  describe google_vertex_ai_featurestore(name: "does_not_exit", region: featurestore['region']) do
  	it { should_not exist }
  end
end
