# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/datafusion/property/instance_maintenance_policy_maintenance_window_recurring_time_window_window'
module GoogleInSpec
  module DataFusion
    module Property
      class InstanceMaintenancePolicyMaintenanceWindowRecurringTimeWindow
        attr_reader :window

        attr_reader :recurrence

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @window = GoogleInSpec::DataFusion::Property::InstanceMaintenancePolicyMaintenanceWindowRecurringTimeWindowWindow.new(args['window'], to_s)
          @recurrence = args['recurrence']
        end

        def to_s
          "#{@parent_identifier} InstanceMaintenancePolicyMaintenanceWindowRecurringTimeWindow"
        end
      end
    end
  end
end
