# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'gcp_backend'
class VertexAITrainingPipelines < GcpResourceBase
  name 'google_vertex_ai_training_pipelines'
  desc 'TrainingPipeline plural resource'
  supports platform: 'gcp'

  attr_reader :table

  filter_table_config = FilterTable.create

  filter_table_config.add(:end_times, field: :end_time)
  filter_table_config.add(:errors, field: :error)
  filter_table_config.add(:display_names, field: :display_name)
  filter_table_config.add(:names, field: :name)
  filter_table_config.add(:input_data_configs, field: :input_data_config)
  filter_table_config.add(:parent_models, field: :parent_model)
  filter_table_config.add(:update_times, field: :update_time)
  filter_table_config.add(:states, field: :state)
  filter_table_config.add(:labels, field: :labels)
  filter_table_config.add(:training_task_definitions, field: :training_task_definition)
  filter_table_config.add(:start_times, field: :start_time)
  filter_table_config.add(:create_times, field: :create_time)
  filter_table_config.add(:training_task_metadata, field: :training_task_metadata)
  filter_table_config.add(:training_task_inputs, field: :training_task_inputs)
  filter_table_config.add(:model_ids, field: :model_id)
  filter_table_config.add(:encryption_specs, field: :encryption_spec)
  filter_table_config.add(:model_to_uploads, field: :model_to_upload)

  filter_table_config.connect(self, :table)

  def initialize(params = {})
    super(params.merge({ use_http_transport: true }))
    @params = params
    @table = fetch_wrapped_resource('trainingPipelines')
  end

  def fetch_wrapped_resource(wrap_path)
    # fetch_resource returns an array of responses (to handle pagination)
    result = @connection.fetch_all(product_url, resource_base_url, @params, 'Get')
    return if result.nil?

    # Conversion of string -> object hash to symbol -> object hash that InSpec needs
    converted = []
    result.each do |response|
      next if response.nil? || !response.key?(wrap_path)
      response[wrap_path].each do |hash|
        hash_with_symbols = {}
        hash.each_key do |key|
          name, value = transform(key, hash)
          hash_with_symbols[name] = value
        end
        converted.push(hash_with_symbols)
      end
    end

    converted
  end

  def transform(key, value)
    return transformers[key].call(value) if transformers.key?(key)

    [key.to_sym, value]
  end

  def transformers
    {
      'endTime' => ->(obj) { return :end_time, obj['endTime'] },
      'error' => ->(obj) { return :error, GoogleInSpec::VertexAI::Property::TrainingPipelineError.new(obj['error'], to_s) },
      'displayName' => ->(obj) { return :display_name, obj['displayName'] },
      'name' => ->(obj) { return :name, obj['name'] },
      'inputDataConfig' => ->(obj) { return :input_data_config, GoogleInSpec::VertexAI::Property::TrainingPipelineInputDataConfig.new(obj['inputDataConfig'], to_s) },
      'parentModel' => ->(obj) { return :parent_model, obj['parentModel'] },
      'updateTime' => ->(obj) { return :update_time, obj['updateTime'] },
      'state' => ->(obj) { return :state, obj['state'] },
      'labels' => ->(obj) { return :labels, GoogleInSpec::VertexAI::Property::TrainingPipelineLabels.new(obj['labels'], to_s) },
      'trainingTaskDefinition' => ->(obj) { return :training_task_definition, obj['trainingTaskDefinition'] },
      'startTime' => ->(obj) { return :start_time, obj['startTime'] },
      'createTime' => ->(obj) { return :create_time, obj['createTime'] },
      'trainingTaskMetadata' => ->(obj) { return :training_task_metadata, obj['trainingTaskMetadata'] },
      'trainingTaskInputs' => ->(obj) { return :training_task_inputs, obj['trainingTaskInputs'] },
      'modelId' => ->(obj) { return :model_id, obj['modelId'] },
      'encryptionSpec' => ->(obj) { return :encryption_spec, GoogleInSpec::VertexAI::Property::TrainingPipelineEncryptionSpec.new(obj['encryptionSpec'], to_s) },
      'modelToUpload' => ->(obj) { return :model_to_upload, GoogleInSpec::VertexAI::Property::TrainingPipelineModelToUpload.new(obj['modelToUpload'], to_s) },
    }
  end

  private

  def product_url(_ = nil)
    'https://{{region}}-aiplatform.googleapis.com/v1/'
  end

  def resource_base_url
    '{{parent}}/trainingPipelines'
  end
end
