

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require "gcp_backend"
require "google/vertexai/property/metadatastoresartifact_labels"
require "google/vertexai/property/metadatastoresartifact_metadata"

# A provider to manage Vertex AI resources.
class VertexAIMetadataStoresArtifact < GcpResourceBase
  name "google_vertex_ai_metadata_stores_artifact"
  desc "MetadataStoresArtifact"
  supports platform: "gcp"

  attr_reader :params
  attr_reader :schema_version
  attr_reader :display_name
  attr_reader :etag
  attr_reader :name
  attr_reader :update_time
  attr_reader :state
  attr_reader :metadata
  attr_reader :uri
  attr_reader :create_time
  attr_reader :schema_title
  attr_reader :description
  attr_reader :labels

  def initialize(params)
    super(params.merge({ use_http_transport: true }))
    @params = params
    @fetched = @connection.fetch(product_url(params[:beta]), resource_base_url, params, "Get")
    parse unless @fetched.nil?
  end

  def parse
    @schema_version = @fetched["schemaVersion"]
    @display_name = @fetched["displayName"]
    @etag = @fetched["etag"]
    @name = @fetched["name"]
    @update_time = @fetched["updateTime"]
    @state = @fetched["state"]
    @metadata = GoogleInSpec::VertexAI::Property::MetadataStoresArtifactMetadata.new(@fetched["metadata"], to_s)
    @uri = @fetched["uri"]
    @create_time = @fetched["createTime"]
    @schema_title = @fetched["schemaTitle"]
    @description = @fetched["description"]
    @labels = GoogleInSpec::VertexAI::Property::MetadataStoresArtifactLabels.new(@fetched["labels"], to_s)
  end

  def exists?
    !@fetched.nil?
  end

  def to_s
    "MetadataStoresArtifact #{@params[:name]}"
  end

  private

  def product_url(_ = nil)
    "https://{{region}}-aiplatform.googleapis.com/v1/"
  end

  def resource_base_url
    "{{name}}"
  end
end
