

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require "gcp_backend"

# A provider to manage Vertex AI resources.
class VertexAIMetadataStoresMetadataSchema < GcpResourceBase
  name "google_vertex_ai_metadata_stores_metadata_schema"
  desc "MetadataStoresMetadataSchema"
  supports platform: "gcp"

  attr_reader :params
  attr_reader :schema_type
  attr_reader :description
  attr_reader :schema_version
  attr_reader :name
  attr_reader :create_time
  attr_reader :schema

  def initialize(params)
    super(params.merge({ use_http_transport: true }))
    @params = params
    @fetched = @connection.fetch(product_url(params[:beta]), resource_base_url, params, "Get")
    parse unless @fetched.nil?
  end

  def parse
    @schema_type = @fetched["schemaType"]
    @description = @fetched["description"]
    @schema_version = @fetched["schemaVersion"]
    @name = @fetched["name"]
    @create_time = @fetched["createTime"]
    @schema = @fetched["schema"]
  end

  def exists?
    !@fetched.nil?
  end

  def to_s
    "MetadataStoresMetadataSchema #{@params[:name]}"
  end

  private

  def product_url(_ = nil)
    "https://{{region}}-aiplatform.googleapis.com/v1/"
  end

  def resource_base_url
    "{{name}}"
  end
end
