# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'gcp_backend'
class ComputeRegionSecurityPolicys < GcpResourceBase
  name 'google_compute_region_security_policies'
  desc 'RegionSecurityPolicy plural resource'
  supports platform: 'gcp'

  attr_reader :table

  filter_table_config = FilterTable.create

  filter_table_config.add(:user_defined_fields, field: :user_defined_fields)
  filter_table_config.add(:kinds, field: :kind)
  filter_table_config.add(:ids, field: :id)
  filter_table_config.add(:creation_timestamps, field: :creation_timestamp)
  filter_table_config.add(:names, field: :name)
  filter_table_config.add(:descriptions, field: :description)
  filter_table_config.add(:rules, field: :rules)
  filter_table_config.add(:adaptive_protection_configs, field: :adaptive_protection_config)
  filter_table_config.add(:ddos_protection_configs, field: :ddos_protection_config)
  filter_table_config.add(:advanced_options_configs, field: :advanced_options_config)
  filter_table_config.add(:recaptcha_options_configs, field: :recaptcha_options_config)
  filter_table_config.add(:fingerprints, field: :fingerprint)
  filter_table_config.add(:self_links, field: :self_link)
  filter_table_config.add(:types, field: :type)
  filter_table_config.add(:labels, field: :labels)
  filter_table_config.add(:label_fingerprints, field: :label_fingerprint)
  filter_table_config.add(:regions, field: :region)

  filter_table_config.connect(self, :table)

  def initialize(params = {})
    super(params.merge({ use_http_transport: true }))
    @params = params
    @table = fetch_wrapped_resource('regionSecurityPolicies')
  end

  def fetch_wrapped_resource(wrap_path)
    # fetch_resource returns an array of responses (to handle pagination)
    result = @connection.fetch_all(product_url, resource_base_url, @params, 'Get')
    return if result.nil?

    # Conversion of string -> object hash to symbol -> object hash that InSpec needs
    converted = []
    result.each do |response|
      next if response.nil? || !response.key?(wrap_path)
      response[wrap_path].each do |hash|
        hash_with_symbols = {}
        hash.each_key do |key|
          name, value = transform(key, hash)
          hash_with_symbols[name] = value
        end
        converted.push(hash_with_symbols)
      end
    end

    converted
  end

  def transform(key, value)
    return transformers[key].call(value) if transformers.key?(key)

    [key.to_sym, value]
  end

  def transformers
    {
      'userDefinedFields' => ->(obj) { return :user_defined_fields, obj['userDefinedFields'] },
      'kind' => ->(obj) { return :kind, obj['kind'] },
      'id' => ->(obj) { return :id, obj['id'] },
      'creationTimestamp' => ->(obj) { return :creation_timestamp, obj['creationTimestamp'] },
      'name' => ->(obj) { return :name, obj['name'] },
      'description' => ->(obj) { return :description, obj['description'] },
      'rules' => ->(obj) { return :rules, obj['rules'] },
      'adaptiveProtectionConfig' => ->(obj) { return :adaptive_protection_config, obj['adaptiveProtectionConfig'] },
      'ddosProtectionConfig' => ->(obj) { return :ddos_protection_config, obj['ddosProtectionConfig'] },
      'advancedOptionsConfig' => ->(obj) { return :advanced_options_config, obj['advancedOptionsConfig'] },
      'recaptchaOptionsConfig' => ->(obj) { return :recaptcha_options_config, obj['recaptchaOptionsConfig'] },
      'fingerprint' => ->(obj) { return :fingerprint, obj['fingerprint'] },
      'selfLink' => ->(obj) { return :self_link, obj['selfLink'] },
      'type' => ->(obj) { return :type, obj['type'] },
      'labels' => ->(obj) { return :labels, GoogleInSpec::Compute::Property::RegionSecurityPolicyLabels.new(obj['labels'], to_s) },
      'labelFingerprint' => ->(obj) { return :label_fingerprint, obj['labelFingerprint'] },
      'region' => ->(obj) { return :region, obj['region'] },
    }
  end

  private

  def product_url(_ = nil)
    'https://compute.googleapis.com/compute/v1/'
  end

  def resource_base_url
    'projects/{{project}}/regions/{{region}}/securityPolicies'
  end
end
