

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require "gcp_backend"
require "google/vertexai/property/featurestore_encryption_spec"
require "google/vertexai/property/featurestore_labels"
require "google/vertexai/property/featurestore_online_serving_config"
require "google/vertexai/property/featurestore_online_serving_config_scaling"

# A provider to manage Vertex AI resources.
class VertexAIFeaturestore < GcpResourceBase
  name "google_vertex_ai_featurestore"
  desc "Featurestore"
  supports platform: "gcp"

  attr_reader :params
  attr_reader :state
  attr_reader :create_time
  attr_reader :etag
  attr_reader :online_storage_ttl_days
  attr_reader :encryption_spec
  attr_reader :labels
  attr_reader :update_time
  attr_reader :name
  attr_reader :online_serving_config

  def initialize(params)
    super(params.merge({ use_http_transport: true }))
    @params = params
    @fetched = @connection.fetch(product_url(params[:beta]), resource_base_url, params, "Get")
    parse unless @fetched.nil?
  end

  def parse
    @state = @fetched["state"]
    @create_time = @fetched["createTime"]
    @etag = @fetched["etag"]
    @online_storage_ttl_days = @fetched["onlineStorageTtlDays"]
    @encryption_spec = GoogleInSpec::VertexAI::Property::FeaturestoreEncryptionSpec.new(@fetched["encryptionSpec"], to_s)
    @labels = GoogleInSpec::VertexAI::Property::FeaturestoreLabels.new(@fetched["labels"], to_s)
    @update_time = @fetched["updateTime"]
    @name = @fetched["name"]
    @online_serving_config = GoogleInSpec::VertexAI::Property::FeaturestoreOnlineServingConfig.new(@fetched["onlineServingConfig"], to_s)
  end

  def exists?
    !@fetched.nil?
  end

  def to_s
    "Featurestore #{@params[:name]}"
  end

  private

  def product_url(_ = nil)
    "https://{{region}}-aiplatform.googleapis.com/v1/"
  end

  def resource_base_url
    "{{name}}"
  end
end
