# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module BigQuery
    module Property
      class TableTimePartitioning
        attr_reader :arguments

        attr_reader :expiration_ms

        attr_reader :field

        attr_reader :type

        def initialize(arguments = nil, parent_identifier = nil)
          @arguments = arguments
          return if arguments.nil?
          @parent_identifier = parent_identifier
          @expiration_ms = arguments['expirationMs']
          @field = arguments['field']
          @type = arguments['type']
        end

        def to_s
          "#{@parent_identifier} TableTimePartitioning"
        end

        def self.un_parse(item, current_path)
          return if item.nil?
          way_to_parse = {
            'expiration_ms' => ->(x, path) { x.nil? ? [] : ["its('#{path}.expiration_ms') { should cmp #{x.inspect} }"] },
            'field' => ->(x, path) { x.nil? ? [] : ["its('#{path}.field') { should cmp #{x.inspect} }"] },
            'type' => ->(x, path) { x.nil? ? [] : ["its('#{path}.type') { should cmp #{x.inspect} }"] },
          }
          way_to_parse.map do |k, v|
            v.call(item.method(k).call, current_path)
          end
        end

        def to_json(*_args)
          @arguments.to_json
        end

        # other is a string representation of this object
        def ==(other)
          @arguments == JSON.parse(other)
        end
      end
    end
  end
end
