# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/datalossprevention/property/deidentifytemplate_deidentify_config_info_type_transformations_transformations_primitive_transformation_crypto_deterministic_config_crypto_key_kms_wrapped'
require 'google/datalossprevention/property/deidentifytemplate_deidentify_config_info_type_transformations_transformations_primitive_transformation_crypto_deterministic_config_crypto_key_transient'
require 'google/datalossprevention/property/deidentifytemplate_deidentify_config_info_type_transformations_transformations_primitive_transformation_crypto_deterministic_config_crypto_key_unwrapped'
module GoogleInSpec
  module DataLossPrevention
    module Property
      class DeidentifyTemplateDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey
        attr_reader :transient

        attr_reader :unwrapped

        attr_reader :kms_wrapped

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @transient = GoogleInSpec::DataLossPrevention::Property::DeidentifyTemplateDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyTransient.new(args['transient'], to_s)
          @unwrapped = GoogleInSpec::DataLossPrevention::Property::DeidentifyTemplateDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyUnwrapped.new(args['unwrapped'], to_s)
          @kms_wrapped = GoogleInSpec::DataLossPrevention::Property::DeidentifyTemplateDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped.new(args['kmsWrapped'], to_s)
        end

        def to_s
          "#{@parent_identifier} DeidentifyTemplateDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey"
        end
      end
    end
  end
end
