# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/datalossprevention/property/dlpjob_risk_details_deidentify_details'
require 'google/datalossprevention/property/dlpjob_risk_details_deidentify_details_deidentify_stats'
require 'google/datalossprevention/property/dlpjob_risk_details_deidentify_details_requested_options'
require 'google/datalossprevention/property/dlpjob_risk_details_deidentify_details_requested_options_snapshot_deidentify_template'
require 'google/datalossprevention/property/dlpjob_risk_details_deidentify_details_requested_options_snapshot_deidentify_template_deidentify_config'
require 'google/datalossprevention/property/dlpjob_risk_details_deidentify_details_requested_options_snapshot_image_redact_template'
require 'google/datalossprevention/property/dlpjob_risk_details_deidentify_details_requested_options_snapshot_image_redact_template_deidentify_config'
require 'google/datalossprevention/property/dlpjob_risk_details_deidentify_details_requested_options_snapshot_structured_deidentify_template'
require 'google/datalossprevention/property/dlpjob_risk_details_deidentify_details_requested_options_snapshot_structured_deidentify_template_deidentify_config'
require 'google/datalossprevention/property/dlpjob_risk_details_deidentify_stats'
require 'google/datalossprevention/property/dlpjob_risk_details_deidentify_stats_requested_options'
require 'google/datalossprevention/property/dlpjob_risk_details_deidentify_stats_requested_options_details'
module GoogleInSpec
  module DataLossPrevention
    module Property
      class DlpJobRiskDetails
        attr_reader :deidentify_details

        attr_reader :deidentify_stats

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @deidentify_details = GoogleInSpec::DataLossPrevention::Property::DlpJobRiskDetailsDeidentifyDetails.new(args['deidentifyDetails'], to_s)
          @deidentify_stats = GoogleInSpec::DataLossPrevention::Property::DlpJobRiskDetailsDeidentifyStats.new(args['deidentifyStats'], to_s)
        end

        def to_s
          "#{@parent_identifier} DlpJobRiskDetails"
        end
      end

      class DlpJobRiskDetailsArray
        def self.parse(value, parent_identifier)
          return if value.nil?
          return DlpJobRiskDetails.new(value, parent_identifier) unless value.is_a?(::Array)
          value.map { |v| DlpJobRiskDetails.new(v, parent_identifier) }
        end
      end
    end
  end
end
