# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/datalossprevention/property/dlpjob_action_details_deidentify_details_requested_options_snapshot_image_redact_template_deidentify_config_record_transformations_field_transformations_condition_expressions_conditions_conditions_field'
require 'google/datalossprevention/property/dlpjob_action_details_deidentify_details_requested_options_snapshot_image_redact_template_deidentify_config_record_transformations_field_transformations_condition_expressions_conditions_conditions_new_value'
require 'google/datalossprevention/property/dlpjob_action_details_deidentify_details_requested_options_snapshot_image_redact_template_deidentify_config_record_transformations_field_transformations_condition_expressions_conditions_conditions_new_value_date_value'
require 'google/datalossprevention/property/dlpjob_action_details_deidentify_details_requested_options_snapshot_image_redact_template_deidentify_config_record_transformations_field_transformations_condition_expressions_conditions_conditions_new_value_time_value'
module GoogleInSpec
  module DataLossPrevention
    module Property
      class DlpJobActionDetailsDeidentifyDetailsRequestedOptionsSnapshotImageRedactTemplateDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditions
        attr_reader :field

        attr_reader :operator

        attr_reader :new_value

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @field = GoogleInSpec::DataLossPrevention::Property::DlpJobActionDetailsDeidentifyDetailsRequestedOptionsSnapshotImageRedactTemplateDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditionsField.new(args['field'], to_s)
          @operator = args['operator']
          @new_value = GoogleInSpec::DataLossPrevention::Property::DlpJobActionDetailsDeidentifyDetailsRequestedOptionsSnapshotImageRedactTemplateDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditionsNewValue.new(args['newValue'], to_s)
        end

        def to_s
          "#{@parent_identifier} DlpJobActionDetailsDeidentifyDetailsRequestedOptionsSnapshotImageRedactTemplateDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditions"
        end
      end

      class DlpJobActionDetailsDeidentifyDetailsRequestedOptionsSnapshotImageRedactTemplateDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditionsArray
        def self.parse(value, parent_identifier)
          return if value.nil?
          return DlpJobActionDetailsDeidentifyDetailsRequestedOptionsSnapshotImageRedactTemplateDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditions.new(value, parent_identifier) unless value.is_a?(::Array)
          value.map { |v| DlpJobActionDetailsDeidentifyDetailsRequestedOptionsSnapshotImageRedactTemplateDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditions.new(v, parent_identifier) }
        end
      end
    end
  end
end
