# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module BigQuery
    module Property
      class TableExternalDataConfigurationBigtableOptionsColumnFamiliesColumns
        attr_reader :encoding

        attr_reader :field_name

        attr_reader :only_read_latest

        attr_reader :qualifier_string

        attr_reader :type

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @encoding = args['encoding']
          @field_name = args['fieldName']
          @only_read_latest = args['onlyReadLatest']
          @qualifier_string = args['qualifierString']
          @type = args['type']
        end

        def to_s
          "#{@parent_identifier} TableExternalDataConfigurationBigtableOptionsColumnFamiliesColumns"
        end
      end

      class TableExternalDataConfigurationBigtableOptionsColumnFamiliesColumnsArray
        def self.parse(value, parent_identifier)
          return if value.nil?
          return TableExternalDataConfigurationBigtableOptionsColumnFamiliesColumns.new(value, parent_identifier) unless value.is_a?(::Array)
          value.map { |v| TableExternalDataConfigurationBigtableOptionsColumnFamiliesColumns.new(v, parent_identifier) }
        end
      end
    end
  end
end
