# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/composer/property/projectlocationenvironment_config_master_authorized_networks_config_cidr_blocks'
module GoogleInSpec
  module Composer
    module Property
      class ProjectLocationEnvironmentConfigMasterAuthorizedNetworksConfig
        attr_reader :enabled

        attr_reader :cidr_blocks

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @enabled = args['enabled']
          @cidr_blocks = GoogleInSpec::Composer::Property::ProjectLocationEnvironmentConfigMasterAuthorizedNetworksConfigCidrBlocksArray.parse(args['cidrBlocks'], to_s)
        end

        def to_s
          "#{@parent_identifier} ProjectLocationEnvironmentConfigMasterAuthorizedNetworksConfig"
        end
      end
    end
  end
end
