

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module Compute
    module Property
      class ImageGuestOsFeatures
        attr_reader :type

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @type = args["type"]
        end

        def to_s
          "#{@parent_identifier} ImageGuestOsFeatures"
        end
      end

      class ImageGuestOsFeaturesArray
        def self.parse(value, parent_identifier)
          return if value.nil?
          return ImageGuestOsFeatures.new(value, parent_identifier) unless value.is_a?(::Array)
          value.map { |v| ImageGuestOsFeatures.new(v, parent_identifier) }
        end
      end
    end
  end
end
