# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/compute/property/machineimage_instance_properties_metadata_items'
module GoogleInSpec
  module Compute
    module Property
      class MachineImageInstancePropertiesMetadata
        attr_reader :kind

        attr_reader :fingerprint

        attr_reader :items

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @kind = args['kind']
          @fingerprint = args['fingerprint']
          @items = GoogleInSpec::Compute::Property::MachineImageInstancePropertiesMetadataItemsArray.parse(args['items'], to_s)
        end

        def to_s
          "#{@parent_identifier} MachineImageInstancePropertiesMetadata"
        end
      end
    end
  end
end
