# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/compute/property/regionurlmap_path_matchers_path_rules_route_action_weighted_backend_services_header_action'
require 'google/compute/property/regionurlmap_pmprrawbsharht_add'
require 'google/compute/property/regionurlmap_pmprrawbsharht_add'
module GoogleInSpec
  module Compute
    module Property
      class RegionUrlMapPathMatchersPathRulesRouteActionWeightedBackendServices
        attr_reader :backend_service

        attr_reader :weight

        attr_reader :header_action

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @backend_service = args['backendService']
          @weight = args['weight']
          @header_action = GoogleInSpec::Compute::Property::RegionUrlMapPathMatchersPathRulesRouteActionWeightedBackendServicesHeaderAction.new(args['headerAction'], to_s)
        end

        def to_s
          "#{@parent_identifier} RegionUrlMapPathMatchersPathRulesRouteActionWeightedBackendServices"
        end
      end

      class RegionUrlMapPathMatchersPathRulesRouteActionWeightedBackendServicesArray
        def self.parse(value, parent_identifier)
          return if value.nil?
          return RegionUrlMapPathMatchersPathRulesRouteActionWeightedBackendServices.new(value, parent_identifier) unless value.is_a?(::Array)
          value.map { |v| RegionUrlMapPathMatchersPathRulesRouteActionWeightedBackendServices.new(v, parent_identifier) }
        end
      end
    end
  end
end
