# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/compute/property/regionsecuritypolicy_configuration_constraints_bgp_peer_asn_ranges'
module GoogleInSpec
  module Compute
    module Property
      class RegionSecurityPolicyConfigurationConstraints
        attr_reader :bgp_md5

        attr_reader :bgp_peer_asn_ranges

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @bgp_md5 = args['bgpMd5']
          @bgp_peer_asn_ranges = GoogleInSpec::Compute::Property::RegionSecurityPolicyConfigurationConstraintsBgpPeerAsnRangesArray.parse(args['bgpPeerAsnRanges'], to_s)
        end

        def to_s
          "#{@parent_identifier} RegionSecurityPolicyConfigurationConstraints"
        end
      end
    end
  end
end
