# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module Compute
    module Property
      class ResourcePolicySnapshotSchedulePolicyScheduleDailySchedule
        attr_reader :days_in_cycle

        attr_reader :start_time

        attr_reader :duration

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @days_in_cycle = args['daysInCycle']
          @start_time = args['startTime']
          @duration = args['duration']
        end

        def to_s
          "#{@parent_identifier} ResourcePolicySnapshotSchedulePolicyScheduleDailySchedule"
        end
      end
    end
  end
end
