# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module Compute
    module Property
      class ResourcePolicyGroupPlacementPolicy
        attr_reader :style

        attr_reader :locality

        attr_reader :vm_count

        attr_reader :availability_domain_count

        attr_reader :collocation

        attr_reader :scope

        attr_reader :tpu_topology

        attr_reader :max_distance

        attr_reader :slice_count

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @style = args['style']
          @locality = args['locality']
          @vm_count = args['vmCount']
          @availability_domain_count = args['availabilityDomainCount']
          @collocation = args['collocation']
          @scope = args['scope']
          @tpu_topology = args['tpuTopology']
          @max_distance = args['maxDistance']
          @slice_count = args['sliceCount']
        end

        def to_s
          "#{@parent_identifier} ResourcePolicyGroupPlacementPolicy"
        end
      end
    end
  end
end
