# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/compute/property/urlmap_path_matchers_path_rules_route_action_cors_policy'
require 'google/compute/property/urlmap_path_matchers_path_rules_route_action_fault_injection_policy'
require 'google/compute/property/urlmap_path_matchers_path_rules_route_action_fault_injection_policy_abort'
require 'google/compute/property/urlmap_path_matchers_path_rules_route_action_fault_injection_policy_delay'
require 'google/compute/property/urlmap_path_matchers_path_rules_route_action_fault_injection_policy_delay_fixed_delay'
require 'google/compute/property/urlmap_path_matchers_path_rules_route_action_request_mirror_policy'
require 'google/compute/property/urlmap_path_matchers_path_rules_route_action_retry_policy'
require 'google/compute/property/urlmap_path_matchers_path_rules_route_action_retry_policy_per_try_timeout'
require 'google/compute/property/urlmap_path_matchers_path_rules_route_action_timeout'
require 'google/compute/property/urlmap_path_matchers_path_rules_route_action_url_rewrite'
require 'google/compute/property/urlmap_path_matchers_path_rules_route_action_weighted_backend_services'
module GoogleInSpec
  module Compute
    module Property
      class UrlMapPathMatchersPathRulesRouteAction
        attr_reader :cors_policy

        attr_reader :fault_injection_policy

        attr_reader :request_mirror_policy

        attr_reader :retry_policy

        attr_reader :timeout

        attr_reader :url_rewrite

        attr_reader :weighted_backend_services

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @cors_policy = GoogleInSpec::Compute::Property::UrlMapPathMatchersPathRulesRouteActionCorsPolicy.new(args['corsPolicy'], to_s)
          @fault_injection_policy = GoogleInSpec::Compute::Property::UrlMapPathMatchersPathRulesRouteActionFaultInjectionPolicy.new(args['faultInjectionPolicy'], to_s)
          @request_mirror_policy = GoogleInSpec::Compute::Property::UrlMapPathMatchersPathRulesRouteActionRequestMirrorPolicy.new(args['requestMirrorPolicy'], to_s)
          @retry_policy = GoogleInSpec::Compute::Property::UrlMapPathMatchersPathRulesRouteActionRetryPolicy.new(args['retryPolicy'], to_s)
          @timeout = GoogleInSpec::Compute::Property::UrlMapPathMatchersPathRulesRouteActionTimeout.new(args['timeout'], to_s)
          @url_rewrite = GoogleInSpec::Compute::Property::UrlMapPathMatchersPathRulesRouteActionUrlRewrite.new(args['urlRewrite'], to_s)
          @weighted_backend_services = GoogleInSpec::Compute::Property::UrlMapPathMatchersPathRulesRouteActionWeightedBackendServicesArray.parse(args['weightedBackendServices'], to_s)
        end

        def to_s
          "#{@parent_identifier} UrlMapPathMatchersPathRulesRouteAction"
        end
      end
    end
  end
end
