# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module Compute
    module Property
      class UrlMapTests
        attr_reader :description

        attr_reader :host

        attr_reader :path

        attr_reader :service

        def initialize(args = nil)
          return if args.nil?
          @description = args['description']
          @host = args['host']
          @path = args['path']
          @service = args['service']
        end
      end

      class UrlMapTestsArray
        def self.parse(value)
          return if value.nil?
          return UrlMapTests.new(value) unless value.is_a?(::Array)
          value.map { |v| UrlMapTests.new(v) }
        end
      end
    end
  end
end
